### ISSUE TITLE
Add documentation on how to use feature flags

### ISSUE THREAD

**Issue by hobofan** [autumnai/collenchyma#36]
Since we heavily use feature flags for frameworks across all plugins, we will want a documentation on how to use them (in combinatinon with plugins) to lower the barrier of entry.

Example:
```toml
[dependencies]
collenchyma      = { version = "~0.0.6", default-features = false }
collenchyma-blas = { version = "0.1", default-features = false }
collenchyma-nn   = { version = "0.1.0", default-features = false }

[features]
default = ["native", "cuda", "opencl"]
native  = ["collenchyma/native", "collenchyma-blas/native", "collenchyma-nn/native"]
cuda    = ["collenchyma/cuda", "collenchyma-blas/cuda", "collenchyma-nn/cuda"]
opencl  = ["collenchyma/opencl", "collenchyma-blas/opencl", "collenchyma-nn/opencl"]
```
